// Copyright (c) 2026 AI anime
/**
 * Canvas shell 的内部依赖面。仅供本目录使用，避免内部组件反向加载全量 public 门面。
 */
export { captureCurrentViewport, jumpToBookmark } from "@/modules/creative_canvas/application/bookmarkActions";
export type { HistoryNodeMeta } from "@/modules/creative_canvas/application/generationHistoryAssets";
export { canvasEventBus } from "@/modules/creative_canvas/canvasEventComposition";
export { useCanvasStore } from "@/modules/creative_canvas/canvasStoreComposition";
export { DEFAULT_ASPECT_RATIO } from "@/modules/creative_canvas/domain/aspectRatio";
export { extractCanvasAssets } from "@/modules/creative_canvas/domain/canvasAssets";
export { deriveNodeDropInfo } from "@/modules/creative_canvas/domain/canvasCommitSource";
export { CANVAS_NODE_TYPES } from "@/modules/creative_canvas/domain/canvasConnection";
export { canvasNodeIntersectsSelectionRect, DEFAULT_CANVAS_NODE_WIDTH, getTopLevelCanvasBounds, hasVisibleTopLevelCanvasNode } from "@/modules/creative_canvas/domain/canvasGeometry";
export type { AudioNodeData, BeatContextNodeData, CanvasEdge, CanvasNode, CanvasNodeData, CanvasNodeType, ExportImageNodeData, GroupNodeData, ImageEditNodeData, ImageGenNodeData, Pano360ViewerNodeData, ScriptNodeData, SkillNodeData, StoryboardGenNodeData, StoryboardSplitNodeData, StyleNodeData, TextAnnotationNodeData, ThreeDWorldNodeData, UploadImageNodeData, VideoComposeNodeData, VideoNodeData, VideoStoryNodeData } from "@/modules/creative_canvas/domain/canvasNodeData";
export { resolveCanvasNodeSourceImageUrl } from "@/modules/creative_canvas/domain/canvasNodeImageSource";
export { isAudioNode, isExportImageNode, isGroupNode, isImageEditNode, isImageGenNode, isPano360ViewerNode, isProtectedProjectionGroupNode, isStoryboardGroupNode, isUploadNode, isVideoNode } from "@/modules/creative_canvas/domain/canvasNodePredicates";
export { getNodeDefinition } from "@/modules/creative_canvas/domain/canvasNodeRegistry";
export { computeSnapAlign } from "@/modules/creative_canvas/domain/canvasSnapAlignment";
export type { GridActionRequest } from "@/modules/creative_canvas/domain/gridAction";
export { EXPORT_RESULT_NODE_DEFAULT_WIDTH, EXPORT_RESULT_NODE_LAYOUT_HEIGHT } from "@/modules/creative_canvas/domain/imageNodeLayout";
export { isPresetManagedEdge, isPresetManagedNode, nodeMainlineFlags } from "@/modules/creative_canvas/domain/mainlineNodeFlags";
export { projectNodeActionToolbarShell } from "@/modules/creative_canvas/domain/nodeActionToolbarShellModel";
export { resolveNodeDisplayName } from "@/modules/creative_canvas/domain/nodeDisplay";
export type { CanvasExportResultKind } from "@/modules/creative_canvas/domain/nodeDisplay";
export { NODE_SELECTION_MENU_ADD_NODE_TYPES } from "@/modules/creative_canvas/domain/nodeSelectionMenuModel";
export { getStoryboardCellPreview } from "@/modules/creative_canvas/domain/storyboardCellPreview";
export type { StoryboardCellPreviewPorts } from "@/modules/creative_canvas/domain/storyboardCellPreview";
export { useAssetDropStore } from "@/modules/creative_canvas/presentation/assetDropStore";
export { AudioNodeToolbarActionsView } from "@/modules/creative_canvas/presentation/AudioNodeToolbarActionsView";
export { AudioNodeView } from "@/modules/creative_canvas/presentation/AudioNodeView";
export { BackToNodesHintView } from "@/modules/creative_canvas/presentation/BackToNodesHintView";
export { BeatContextNodeView } from "@/modules/creative_canvas/presentation/BeatContextNodeView";
export { CanvasContextMenu } from "@/modules/creative_canvas/presentation/CanvasContextMenu";
export { CANVAS_CONTROL_GLASS_CLASS, CANVAS_CONTROL_ICON_BUTTON_ACTIVE_CLASS, CANVAS_CONTROL_ICON_BUTTON_CLASS } from "@/modules/creative_canvas/presentation/canvasControlStyles";
export { CanvasFpsMeter } from "@/modules/creative_canvas/presentation/CanvasFpsMeter";
export { CanvasHistoryAssetsModal } from "@/modules/creative_canvas/presentation/CanvasHistoryAssetsModal";
export { PAN_ACTIVATION_KEY_CODE } from "@/modules/creative_canvas/presentation/canvasInteractionTargets";
export { CanvasMinimapBookmarksOverlay } from "@/modules/creative_canvas/presentation/CanvasMinimapBookmarksOverlay";
export { CanvasMinimapButton } from "@/modules/creative_canvas/presentation/CanvasMinimapButton";
export { NODE_ACTION_TOOLBAR_MENU_CONTENT_CLASS, NODE_ACTION_TOOLBAR_MENU_ITEM_CLASS, NODE_ACTION_TOOLBAR_TEXT_BUTTON_CLASS } from "@/modules/creative_canvas/presentation/canvasNodeActionToolbarStyles";
export { canvasNodeFrameClass } from "@/modules/creative_canvas/presentation/canvasNodeFrameStyles";
export type { NodeSelectionMenuNodeDefinition } from "@/modules/creative_canvas/presentation/CanvasNodeMenuPrimitives";
export { NODE_TOOLBAR_ALIGN, NODE_TOOLBAR_CLASS, NODE_TOOLBAR_OFFSET, NODE_TOOLBAR_POSITION } from "@/modules/creative_canvas/presentation/canvasNodeToolbarConfig";
export { CanvasQuickActionBar } from "@/modules/creative_canvas/presentation/CanvasQuickActionBar";
export type { CanvasQuickActionBarProps } from "@/modules/creative_canvas/presentation/CanvasQuickActionBar";
export { CanvasSnapAlignButton } from "@/modules/creative_canvas/presentation/CanvasSnapAlignButton";
export { CanvasSnapAlignGuides } from "@/modules/creative_canvas/presentation/CanvasSnapAlignGuides";
export { CanvasConnectionPreviewOverlay, CanvasTransientOverlays } from "@/modules/creative_canvas/presentation/CanvasTransientOverlays";
export { CanvasZoomControl } from "@/modules/creative_canvas/presentation/CanvasZoomControl";
export { GroupNodeToolbarActionsView } from "@/modules/creative_canvas/presentation/GroupNodeToolbarActionsView";
export { GroupNodeView } from "@/modules/creative_canvas/presentation/GroupNodeView";
export type { GroupNodeViewBindings } from "@/modules/creative_canvas/presentation/GroupNodeView";
export { ImageEditNodeView } from "@/modules/creative_canvas/presentation/ImageEditNodeView";
export { ImageEditToolbarActionsView } from "@/modules/creative_canvas/presentation/ImageEditToolbarActionsView";
export { ImageGenNodeView } from "@/modules/creative_canvas/presentation/ImageGenNodeView";
export { ImageGridToolbarActions } from "@/modules/creative_canvas/presentation/ImageGridToolbarActions";
export { ImageNodeToolbarActionsView } from "@/modules/creative_canvas/presentation/ImageNodeToolbarActionsView";
export { ImageNodeView } from "@/modules/creative_canvas/presentation/ImageNodeView";
export { ImageViewerModal } from "@/modules/creative_canvas/presentation/ImageViewerModal";
export { MultiSelectionConnectButton } from "@/modules/creative_canvas/presentation/MultiSelectionConnectButton";
export type { MultiSelectionConnectButtonProps } from "@/modules/creative_canvas/presentation/MultiSelectionConnectButton";
export { NodeActionToolbarView } from "@/modules/creative_canvas/presentation/NodeActionToolbarView";
export { NODE_HEADER_FLOATING_POSITION_CLASS, NodeHeader } from "@/modules/creative_canvas/presentation/NodeHeader";
export { NodeMainlineToolbarActionsView } from "@/modules/creative_canvas/presentation/NodeMainlineToolbarActionsView";
export { NodeManagementToolbarActionsView } from "@/modules/creative_canvas/presentation/NodeManagementToolbarActionsView";
export { NodeOutputToolbarActionsView } from "@/modules/creative_canvas/presentation/NodeOutputToolbarActionsView";
export { NodeResizeHandle } from "@/modules/creative_canvas/presentation/NodeResizeHandle";
export { NodeSelectionMenu } from "@/modules/creative_canvas/presentation/NodeSelectionMenu";
export type { NodeSelectionMenuProps } from "@/modules/creative_canvas/presentation/NodeSelectionMenu";
export { NODE_SIDE_ACTION_BUTTON_CLASS, NODE_SIDE_ACTION_ICON_CLASS, NodeSideActionRail } from "@/modules/creative_canvas/presentation/NodeSideActionRail";
export { Pano360ViewerNodeView } from "@/modules/creative_canvas/presentation/Pano360ViewerNodeView";
export { ScriptNodeView } from "@/modules/creative_canvas/presentation/ScriptNodeView";
export { SkillNodeView } from "@/modules/creative_canvas/presentation/SkillNodeView";
export { useSnapAlignStore } from "@/modules/creative_canvas/presentation/snapAlignStore";
export { StoryboardGenNodeView } from "@/modules/creative_canvas/presentation/StoryboardGenNodeView";
export { StoryboardGroupToolbarView } from "@/modules/creative_canvas/presentation/StoryboardGroupToolbarView";
export { StoryboardNodeView } from "@/modules/creative_canvas/presentation/StoryboardNodeView";
export { StyleNodeView } from "@/modules/creative_canvas/presentation/StyleNodeView";
export { TextAnnotationNodeView } from "@/modules/creative_canvas/presentation/TextAnnotationNodeView";
export { ThreeDWorldNodeView } from "@/modules/creative_canvas/presentation/ThreeDWorldNodeView";
export { UploadNodeView } from "@/modules/creative_canvas/presentation/UploadNodeView";
export { useCanvasCommandSurfaceController } from "@/modules/creative_canvas/presentation/useCanvasCommandSurfaceController";
export type { CanvasCommandHistoryPort } from "@/modules/creative_canvas/presentation/useCanvasCommandSurfaceController";
export type { CanvasHistoryAssetsModalCommandProps, CanvasHistoryAssetsModalController } from "@/modules/creative_canvas/presentation/useCanvasHistoryAssetsModalController";
export { useCanvasRenderSurfaceController } from "@/modules/creative_canvas/presentation/useCanvasRenderSurfaceController";
export { useCanvasSelectionSurfaceController } from "@/modules/creative_canvas/presentation/useCanvasSelectionSurfaceController";
export { useGroupNodeController } from "@/modules/creative_canvas/presentation/useGroupNodeController";
export type { GroupNodeControllerPorts } from "@/modules/creative_canvas/presentation/useGroupNodeController";
export { useGroupNodeToolbarController } from "@/modules/creative_canvas/presentation/useGroupNodeToolbarController";
export { useStoryboardGroupToolbarController } from "@/modules/creative_canvas/presentation/useStoryboardGroupToolbarController";
export { VideoComposeNodeView } from "@/modules/creative_canvas/presentation/VideoComposeNodeView";
export { VideoNodeToolbarActionsView } from "@/modules/creative_canvas/presentation/VideoNodeToolbarActionsView";
export { VideoNodeView } from "@/modules/creative_canvas/presentation/VideoNodeView";
export { VideoStoryNodeView } from "@/modules/creative_canvas/presentation/VideoStoryNodeView";
export { VideoViewerModal } from "@/modules/creative_canvas/presentation/VideoViewerModal";
export { ZoomScaledToolbar } from "@/modules/creative_canvas/presentation/ZoomScaledToolbar";
