import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const VERSION_PATTERN = /^\d+\.\d+\.\d+$/;

export function nextPatchVersion(version) {
  if (!VERSION_PATTERN.test(version)) {
    throw new Error(`版本号不是 x.y.z 格式：${version}`);
  }
  const [major, minor, patch] = version.split(".").map(Number);
  return `${major}.${minor}.${patch + 1}`;
}

function read(root, relativePath) {
  return readFileSync(resolve(root, relativePath), "utf8");
}

function write(root, relativePath, content) {
  writeFileSync(resolve(root, relativePath), content, "utf8");
}

function requiredMatch(content, pattern, label) {
  const match = content.match(pattern);
  if (!match) throw new Error(`未找到 ${label} 的版本号`);
  return match[1];
}

function replaceRequired(content, pattern, replacement, label) {
  if (!pattern.test(content)) throw new Error(`无法更新 ${label}`);
  pattern.lastIndex = 0;
  return content.replace(pattern, replacement);
}

export function readWorkspaceVersion(root) {
  const versions = new Map([
    [
      "pyproject.toml",
      requiredMatch(
        read(root, "pyproject.toml"),
        /^version = "([^"]+)"/m,
        "pyproject.toml",
      ),
    ],
    [
      "desktop/package.json",
      requiredMatch(
        read(root, "desktop/package.json"),
        /^\s*"version":\s*"([^"]+)"/m,
        "desktop/package.json",
      ),
    ],
    [
      "uv.lock",
      requiredMatch(
        read(root, "uv.lock"),
        /\[\[package\]\]\r?\nname = "ai-anime"\r?\nversion = "([^"]+)"/,
        "uv.lock",
      ),
    ],
    [
      "frontend/vite.config.ts",
      requiredMatch(
        read(root, "frontend/vite.config.ts"),
        /const DEFAULT_APP_VERSION = "([^"]+)";/,
        "frontend/vite.config.ts",
      ),
    ],
    [
      "README.md",
      requiredMatch(
        read(root, "README.md"),
        /当前客户端版本：`([^`]+)`。/,
        "README.md",
      ),
    ],
  ]);
  const unique = new Set(versions.values());
  if (unique.size !== 1) {
    throw new Error(
      `版本文件不一致：${[...versions].map(([file, version]) => `${file}=${version}`).join("，")}`,
    );
  }
  return versions.values().next().value;
}

function normalizedRecord(value, fallback) {
  const text = String(value || "")
    .replace(/[\u0000-\u001f\u007f]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return (text || fallback).slice(0, 800);
}

function renderReleaseNotes(version, context) {
  const sourceCommit = normalizedRecord(context.sourceCommit, "unknown");
  const buildNumber = normalizedRecord(context.buildNumber, "manual");
  const message = normalizedRecord(context.message, "未提供提交说明");
  return `---
version: ${version}
attention: medium
---
# v${version}

## User-facing Highlights (zh)

- **来源提交**: 本版本由 Gitee Go 根据提交 \`${sourceCommit}\` 自动生成，流水线构建编号为 \`${buildNumber}\`。
- **变更摘要**: ${message}
- **版本同步**: Python 包、Electron 安装器、前端版本兜底、依赖锁文件和 README 已统一更新为 ${version}。
- **更新提示**: 更新窗口将展示本版本记录；安装完成后请重新启动客户端，使本地后端、Hermes 和 Electron 主进程全部切换到新版本。

## User-facing Highlights (en)

- **Source commit**: Generated by Gitee Go from commit \`${sourceCommit}\` in pipeline build \`${buildNumber}\`.
- **Change summary**: ${message}
- **Version synchronization**: Python, Electron, frontend fallback, dependency lock, and README versions are synchronized to ${version}.
- **Update notice**: Restart the desktop client after installation so the local backend, Hermes, and Electron main process all use the new version.
`;
}

function gitValue(root, args, fallback) {
  try {
    return execFileSync("git", args, {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return fallback;
  }
}

export function bumpWorkspaceVersion(root, targetVersion, context = {}) {
  const currentVersion = readWorkspaceVersion(root);
  if (!VERSION_PATTERN.test(targetVersion)) {
    throw new Error(`目标版本号不是 x.y.z 格式：${targetVersion}`);
  }
  if (targetVersion === currentVersion) {
    throw new Error(`目标版本 ${targetVersion} 与当前版本相同`);
  }

  write(
    root,
    "pyproject.toml",
    replaceRequired(
      read(root, "pyproject.toml"),
      /^version = "[^"]+"/m,
      `version = "${targetVersion}"`,
      "pyproject.toml",
    ),
  );
  write(
    root,
    "desktop/package.json",
    replaceRequired(
      read(root, "desktop/package.json"),
      /^(\s*"version":\s*)"[^"]+"/m,
      `$1"${targetVersion}"`,
      "desktop/package.json",
    ),
  );
  write(
    root,
    "uv.lock",
    replaceRequired(
      read(root, "uv.lock"),
      /(\[\[package\]\]\r?\nname = "ai-anime"\r?\nversion = ")([^"]+)(")/,
      `$1${targetVersion}$3`,
      "uv.lock",
    ),
  );
  write(
    root,
    "frontend/vite.config.ts",
    replaceRequired(
      read(root, "frontend/vite.config.ts"),
      /const DEFAULT_APP_VERSION = "[^"]+";/,
      `const DEFAULT_APP_VERSION = "${targetVersion}";`,
      "frontend/vite.config.ts",
    ),
  );
  write(
    root,
    "README.md",
    replaceRequired(
      read(root, "README.md"),
      /当前客户端版本：`[^`]+`。/,
      `当前客户端版本：\`${targetVersion}\`。`,
      "README.md",
    ),
  );
  write(
    root,
    "docs/cloud-integration-handoff.md",
    replaceRequired(
      read(root, "docs/cloud-integration-handoff.md"),
      /客户端 `[^`]+` 固定使用/,
      `客户端 \`${targetVersion}\` 固定使用`,
      "docs/cloud-integration-handoff.md",
    ),
  );
  write(
    root,
    "src/ai_anime/release-notes.md",
    renderReleaseNotes(targetVersion, context),
  );
  return { currentVersion, targetVersion };
}

function argumentValue(args, name) {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] : null;
}

function runCli() {
  const args = process.argv.slice(2);
  const root = resolve(fileURLToPath(new URL("../..", import.meta.url)));
  const currentVersion = readWorkspaceVersion(root);
  const explicitVersion = argumentValue(args, "--version");
  const targetVersion = args.includes("--patch")
    ? nextPatchVersion(currentVersion)
    : explicitVersion;
  if (!targetVersion) {
    throw new Error("请传入 --patch 或 --version x.y.z");
  }

  const sourceCommit =
    process.env.GITEE_COMMIT || gitValue(root, ["rev-parse", "HEAD"], "unknown");
  const message = gitValue(
    root,
    ["show", "-s", "--format=%B", sourceCommit],
    process.env.GITEE_COMMIT_MESSAGE || "未提供提交说明",
  );
  const result = bumpWorkspaceVersion(root, targetVersion, {
    sourceCommit,
    buildNumber: process.env.GITEE_PIPELINE_BUILD_NUMBER || "manual",
    message,
  });
  process.stdout.write(
    `版本已从 ${result.currentVersion} 更新为 ${result.targetVersion}\n`,
  );
}

const entryPath = process.argv[1] ? resolve(process.argv[1]) : "";
if (entryPath && fileURLToPath(import.meta.url) === entryPath) {
  runCli();
}
