"""Creative Canvas domain rules."""

from ai_anime.modules.creative_canvas.domain.audio_library import (
    CREATIVE_CANVAS_AUDIO_AGE_GROUP_LABELS,
)
from ai_anime.modules.creative_canvas.domain.canvas_documents import (
    detected_reference_ids_from_beat_context_data,
    first_text_value,
    is_preset_managed_canvas_node,
    merge_restored_preset_canvas,
    prepare_creative_canvas_payload_for_write,
    stamp_canvas_mainline_context_project_id,
    sync_frame_context_reference_edges,
)
from ai_anime.modules.creative_canvas.domain.canvas_events import (
    CreativeCanvasEventActor,
    canvas_event_actor,
)
from ai_anime.modules.creative_canvas.domain.canvas_commits import (
    CREATIVE_CANVAS_GLOBAL_SLOT_KINDS,
    CREATIVE_CANVAS_SCENE_SLOT_KINDS,
    CreativeCanvasImpactBeat,
    compute_creative_canvas_slot_impact,
    creative_canvas_slot_asset_key,
    is_global_creative_canvas_slot,
)
from ai_anime.modules.creative_canvas.domain.canvas_assets import (
    is_creative_canvas_scene_library_role,
    project_creative_canvas_asset_record,
    project_creative_canvas_beat_context_asset,
)
from ai_anime.modules.creative_canvas.domain.canvas_projections import (
    default_push_target_for_preset,
    merge_projected_preset_canvas,
    preset_facts_signature,
    preset_facts_signature_from_payload,
    projection_facts_signature_from_payload,
    projection_group_label,
    remove_projected_preset_canvas,
    stamp_preset_facts_signature,
    stamp_projection_key,
    stamp_projection_metadata,
    wrap_projection_payload_in_group,
)
from ai_anime.modules.creative_canvas.domain.image_to_3gs import (
    CreativeCanvasImageToThreeGsPlan,
    CreativeCanvasImageToThreeGsSourceKind,
    InvalidCreativeCanvasImageToThreeGsSource,
    infer_image_to_three_gs_scene_id,
    plan_image_to_three_gs,
)
from ai_anime.modules.creative_canvas.domain.image_editing import (
    CreativeCanvasImageCameraConfig,
    CreativeCanvasImageStyleConfig,
    InvalidCreativeCanvasImageAspectRatio,
    InvalidCreativeCanvasImageSize,
    build_image_erase_prompt,
    build_image_outpaint_prompt,
    build_image_redraw_prompt,
    build_image_upscale_prompt,
    plan_outpaint_canvas,
    resolve_original_image_aspect_ratio,
    resolve_requested_image_aspect_ratio,
)
from ai_anime.modules.creative_canvas.domain.image_editing_prompts import (
    InvalidCreativeCanvasImageTemplateMode,
    build_image_multi_view_prompt,
    build_image_relight_prompt,
    build_image_template_edit_prompt,
    resolve_image_template_aspect_ratio,
    resolve_image_template_image_size,
)
from ai_anime.modules.creative_canvas.domain.media import (
    CreativeCanvasScreenshotTooLarge,
    InvalidCreativeCanvasPngScreenshot,
    decode_png_screenshot,
    normalize_screenshot_label,
)
from ai_anime.modules.creative_canvas.domain.mark_detection import (
    CreativeCanvasMarkSelection,
    CreativeCanvasMarkSelectionRequired,
)
from ai_anime.modules.creative_canvas.domain.principal import canvas_actor_id
from ai_anime.modules.creative_canvas.domain.preset_aspect_ratio import (
    CREATIVE_CANVAS_PRESET_IMAGE_ASPECT_RATIOS,
    context_preset_sketch_aspect_ratio,
    nearest_preset_image_aspect_ratio,
    normalize_preset_image_aspect_ratio,
    parse_preset_aspect_ratio,
    project_preset_sketch_aspect_ratio,
)
from ai_anime.modules.creative_canvas.domain.preset_context import (
    as_preset_list,
    extract_preset_visual_markers,
    normalize_preset_scene_name,
    preset_identity_character,
    preset_identity_id,
    preset_identity_name,
    preset_prop_id,
    real_preset_identity_ids,
    real_preset_prop_ids,
    replace_preset_beat_markers,
)
from ai_anime.modules.creative_canvas.domain.preset_identity import (
    canvas_id_for_preset,
    preset_key_for_request,
    safe_creative_canvas_identifier_fragment,
)
from ai_anime.modules.creative_canvas.domain.preset_reference import (
    PresetRef,
    preset_ref_mainline_context,
)
from ai_anime.modules.creative_canvas.domain.video_generation import (
    build_freezone_image_to_video_prompt,
    build_freezone_keyframe_video_prompt,
    build_freezone_omni_video_prompt,
    build_freezone_video_prompt,
    get_video_camera_template,
    get_video_camera_templates,
    normalize_video_aspect_ratio,
    normalize_video_resolution,
    summarize_omni_reference_counts,
    validate_omni_reference_limits,
)
from ai_anime.modules.creative_canvas.domain.video_processing import (
    CreativeCanvasVideoEraseMode,
    validate_video_composition_media_item_count,
    validate_video_composition_source_range,
    validate_video_composition_track_count,
    validate_video_composition_video_item_count,
    validate_video_erase_box,
)
from ai_anime.modules.creative_canvas.domain.video_asset_library import (
    delete_video_asset_library_item,
    upsert_video_asset_library_item,
)

__all__ = [
    "PresetRef",
    "preset_ref_mainline_context",
    "CREATIVE_CANVAS_PRESET_IMAGE_ASPECT_RATIOS",
    "context_preset_sketch_aspect_ratio",
    "nearest_preset_image_aspect_ratio",
    "normalize_preset_image_aspect_ratio",
    "parse_preset_aspect_ratio",
    "project_preset_sketch_aspect_ratio",
    "as_preset_list",
    "extract_preset_visual_markers",
    "normalize_preset_scene_name",
    "preset_identity_character",
    "preset_identity_id",
    "preset_identity_name",
    "preset_prop_id",
    "real_preset_identity_ids",
    "real_preset_prop_ids",
    "replace_preset_beat_markers",
    "CREATIVE_CANVAS_AUDIO_AGE_GROUP_LABELS",
    "CREATIVE_CANVAS_GLOBAL_SLOT_KINDS",
    "CREATIVE_CANVAS_SCENE_SLOT_KINDS",
    "CreativeCanvasImageToThreeGsPlan",
    "CreativeCanvasImageToThreeGsSourceKind",
    "CreativeCanvasImageCameraConfig",
    "CreativeCanvasImageStyleConfig",
    "CreativeCanvasEventActor",
    "CreativeCanvasImpactBeat",
    "CreativeCanvasScreenshotTooLarge",
    "CreativeCanvasMarkSelection",
    "CreativeCanvasMarkSelectionRequired",
    "CreativeCanvasVideoEraseMode",
    "InvalidCreativeCanvasPngScreenshot",
    "InvalidCreativeCanvasImageToThreeGsSource",
    "InvalidCreativeCanvasImageAspectRatio",
    "InvalidCreativeCanvasImageSize",
    "InvalidCreativeCanvasImageTemplateMode",
    "build_image_erase_prompt",
    "build_image_multi_view_prompt",
    "build_image_outpaint_prompt",
    "build_image_relight_prompt",
    "build_image_redraw_prompt",
    "build_image_template_edit_prompt",
    "build_image_upscale_prompt",
    "build_freezone_image_to_video_prompt",
    "build_freezone_keyframe_video_prompt",
    "build_freezone_omni_video_prompt",
    "build_freezone_video_prompt",
    "canvas_actor_id",
    "canvas_event_actor",
    "canvas_id_for_preset",
    "compute_creative_canvas_slot_impact",
    "creative_canvas_slot_asset_key",
    "decode_png_screenshot",
    "default_push_target_for_preset",
    "detected_reference_ids_from_beat_context_data",
    "first_text_value",
    "infer_image_to_three_gs_scene_id",
    "is_preset_managed_canvas_node",
    "is_global_creative_canvas_slot",
    "is_creative_canvas_scene_library_role",
    "merge_projected_preset_canvas",
    "merge_restored_preset_canvas",
    "preset_facts_signature",
    "preset_facts_signature_from_payload",
    "preset_key_for_request",
    "prepare_creative_canvas_payload_for_write",
    "project_creative_canvas_asset_record",
    "project_creative_canvas_beat_context_asset",
    "projection_facts_signature_from_payload",
    "projection_group_label",
    "normalize_screenshot_label",
    "normalize_video_aspect_ratio",
    "normalize_video_resolution",
    "plan_image_to_three_gs",
    "plan_outpaint_canvas",
    "resolve_original_image_aspect_ratio",
    "resolve_image_template_aspect_ratio",
    "resolve_image_template_image_size",
    "resolve_requested_image_aspect_ratio",
    "safe_creative_canvas_identifier_fragment",
    "remove_projected_preset_canvas",
    "get_video_camera_template",
    "get_video_camera_templates",
    "summarize_omni_reference_counts",
    "stamp_canvas_mainline_context_project_id",
    "stamp_preset_facts_signature",
    "stamp_projection_key",
    "stamp_projection_metadata",
    "sync_frame_context_reference_edges",
    "validate_omni_reference_limits",
    "validate_video_composition_media_item_count",
    "validate_video_composition_source_range",
    "validate_video_composition_track_count",
    "validate_video_composition_video_item_count",
    "validate_video_erase_box",
    "wrap_projection_payload_in_group",
    "delete_video_asset_library_item",
    "upsert_video_asset_library_item",
]
