"""Creative Canvas domain rules."""

from ai_anime.modules.creative_canvas.domain.audio_library import (
    CREATIVE_CANVAS_AUDIO_AGE_GROUP_LABELS,
)
from ai_anime.modules.creative_canvas.domain.canvas_documents import (
    detected_reference_ids_from_beat_context_data,
    first_text_value,
    is_preset_managed_canvas_node,
    merge_restored_preset_canvas,
    prepare_creative_canvas_payload_for_write,
    stamp_canvas_mainline_context_project_id,
    sync_frame_context_reference_edges,
)
from ai_anime.modules.creative_canvas.domain.canvas_events import (
    CreativeCanvasEventActor,
    canvas_event_actor,
)
from ai_anime.modules.creative_canvas.domain.canvas_projections import (
    default_push_target_for_preset,
    merge_projected_preset_canvas,
    preset_facts_signature,
    preset_facts_signature_from_payload,
    projection_facts_signature_from_payload,
    projection_group_label,
    remove_projected_preset_canvas,
    stamp_preset_facts_signature,
    stamp_projection_key,
    stamp_projection_metadata,
    wrap_projection_payload_in_group,
)
from ai_anime.modules.creative_canvas.domain.image_to_3gs import (
    CreativeCanvasImageToThreeGsPlan,
    CreativeCanvasImageToThreeGsSourceKind,
    InvalidCreativeCanvasImageToThreeGsSource,
    infer_image_to_three_gs_scene_id,
    plan_image_to_three_gs,
)
from ai_anime.modules.creative_canvas.domain.image_editing import (
    DEFAULT_CREATIVE_CANVAS_IMAGE_MODEL,
    SUPPORTED_CREATIVE_CANVAS_IMAGE_PROVIDERS,
    CreativeCanvasImageCameraConfig,
    CreativeCanvasImageStyleConfig,
    InvalidCreativeCanvasImageAspectRatio,
    InvalidCreativeCanvasImageSize,
    UnsupportedCreativeCanvasImageProvider,
    build_image_erase_prompt,
    build_image_outpaint_prompt,
    build_image_redraw_prompt,
    build_image_upscale_prompt,
    plan_outpaint_canvas,
    resolve_original_image_aspect_ratio,
    resolve_image_provider,
    resolve_requested_image_aspect_ratio,
)
from ai_anime.modules.creative_canvas.domain.image_editing_prompts import (
    InvalidCreativeCanvasImageTemplateMode,
    build_image_multi_view_prompt,
    build_image_relight_prompt,
    build_image_template_edit_prompt,
    resolve_image_template_aspect_ratio,
)
from ai_anime.modules.creative_canvas.domain.media import (
    CreativeCanvasScreenshotTooLarge,
    InvalidCreativeCanvasPngScreenshot,
    decode_png_screenshot,
    normalize_screenshot_label,
)
from ai_anime.modules.creative_canvas.domain.mark_detection import (
    CreativeCanvasMarkSelection,
    CreativeCanvasMarkSelectionRequired,
)
from ai_anime.modules.creative_canvas.domain.principal import canvas_actor_id
from ai_anime.modules.creative_canvas.domain.video_generation import (
    build_freezone_image_to_video_prompt,
    build_freezone_keyframe_video_prompt,
    build_freezone_omni_video_prompt,
    build_freezone_video_prompt,
    get_video_camera_template,
    get_video_camera_templates,
    normalize_video_aspect_ratio,
    normalize_video_resolution,
    summarize_omni_reference_counts,
    validate_omni_reference_limits,
)
from ai_anime.modules.creative_canvas.domain.video_processing import (
    CreativeCanvasVideoEraseMode,
    validate_video_composition_media_item_count,
    validate_video_composition_source_range,
    validate_video_composition_track_count,
    validate_video_composition_video_item_count,
    validate_video_erase_box,
)
from ai_anime.modules.creative_canvas.domain.video_asset_library import (
    delete_video_asset_library_item,
    upsert_video_asset_library_item,
)

__all__ = [
    "CREATIVE_CANVAS_AUDIO_AGE_GROUP_LABELS",
    "DEFAULT_CREATIVE_CANVAS_IMAGE_MODEL",
    "CreativeCanvasImageToThreeGsPlan",
    "CreativeCanvasImageToThreeGsSourceKind",
    "CreativeCanvasImageCameraConfig",
    "CreativeCanvasImageStyleConfig",
    "CreativeCanvasEventActor",
    "SUPPORTED_CREATIVE_CANVAS_IMAGE_PROVIDERS",
    "CreativeCanvasScreenshotTooLarge",
    "CreativeCanvasMarkSelection",
    "CreativeCanvasMarkSelectionRequired",
    "CreativeCanvasVideoEraseMode",
    "InvalidCreativeCanvasPngScreenshot",
    "InvalidCreativeCanvasImageToThreeGsSource",
    "InvalidCreativeCanvasImageAspectRatio",
    "InvalidCreativeCanvasImageSize",
    "InvalidCreativeCanvasImageTemplateMode",
    "UnsupportedCreativeCanvasImageProvider",
    "build_image_erase_prompt",
    "build_image_multi_view_prompt",
    "build_image_outpaint_prompt",
    "build_image_relight_prompt",
    "build_image_redraw_prompt",
    "build_image_template_edit_prompt",
    "build_image_upscale_prompt",
    "build_freezone_image_to_video_prompt",
    "build_freezone_keyframe_video_prompt",
    "build_freezone_omni_video_prompt",
    "build_freezone_video_prompt",
    "canvas_actor_id",
    "canvas_event_actor",
    "decode_png_screenshot",
    "default_push_target_for_preset",
    "detected_reference_ids_from_beat_context_data",
    "first_text_value",
    "infer_image_to_three_gs_scene_id",
    "is_preset_managed_canvas_node",
    "merge_projected_preset_canvas",
    "merge_restored_preset_canvas",
    "preset_facts_signature",
    "preset_facts_signature_from_payload",
    "prepare_creative_canvas_payload_for_write",
    "projection_facts_signature_from_payload",
    "projection_group_label",
    "normalize_screenshot_label",
    "normalize_video_aspect_ratio",
    "normalize_video_resolution",
    "plan_image_to_three_gs",
    "plan_outpaint_canvas",
    "resolve_original_image_aspect_ratio",
    "resolve_image_provider",
    "resolve_image_template_aspect_ratio",
    "resolve_requested_image_aspect_ratio",
    "remove_projected_preset_canvas",
    "get_video_camera_template",
    "get_video_camera_templates",
    "summarize_omni_reference_counts",
    "stamp_canvas_mainline_context_project_id",
    "stamp_preset_facts_signature",
    "stamp_projection_key",
    "stamp_projection_metadata",
    "sync_frame_context_reference_edges",
    "validate_omni_reference_limits",
    "validate_video_composition_media_item_count",
    "validate_video_composition_source_range",
    "validate_video_composition_track_count",
    "validate_video_composition_video_item_count",
    "validate_video_erase_box",
    "wrap_projection_payload_in_group",
    "delete_video_asset_library_item",
    "upsert_video_asset_library_item",
]
