"""Stable application API exposed by Model Usage."""

from ai_anime.modules.model_usage.domain import (
    MODEL_QUOTA_EXCEEDED_MESSAGE,
    REMOTE_MODEL_QUOTA_CODE,
    ModelQuotaExceededError,
    ModelQuotaExceededStop,
    find_model_quota_error,
    find_model_quota_stop,
    is_model_quota_error,
    iter_exception_chain,
    model_quota_payload,
)
from ai_anime.modules.model_usage.domain.official_defaults import (
    DEFAULT_COGNEE_EMBEDDING_DIM,
    DEFAULT_EMBEDDING_BATCH_SIZE,
)
from ai_anime.modules.model_usage.domain.model_route import (
    ModelRoute,
    resolve_model_route,
)
from ai_anime.modules.model_usage.infrastructure.audio_request_usage import (
    count_audio_scope_attempts,
    get_audio_request_usage_db_path,
    record_audio_generation_attempt,
    update_audio_generation_attempt,
)
from ai_anime.modules.model_usage.infrastructure.image_request_usage import (
    count_image_scope_attempts,
    get_image_request_usage_db_path,
    get_image_usage_summary,
    infer_episode_from_path,
    infer_project_output_dir,
    record_image_request,
    update_image_request_status,
)
from ai_anime.modules.model_usage.infrastructure.model_access_policy import (
    MODEL_ACCESS_STDIN_ENV,
    RuntimeModelAccess,
    RuntimeModelAssignment,
    RuntimeModelCapability,
    configure_model_access,
    is_byok_allowed,
    load_model_access_from_stdin,
    model_access_configured,
    normalize_video_workflow,
    require_model_admin_token,
    resolve_model_assignment_for_role,
    resolve_model_for_role,
    runtime_model_access,
    runtime_model_capability,
    serialize_model_access_for_subprocess,
)
from ai_anime.modules.model_usage.infrastructure.model_audio_transport import (
    ModelAudioTransportError,
    ModelAudioWriteResult,
    write_model_audio_music,
    write_model_audio_speech,
    write_model_audio_voice_design,
)
from ai_anime.modules.model_usage.infrastructure.model_gateway_settings import (
    MODE_MIXED,
    EffectiveCogneeEmbeddingConfig,
    EffectiveModelGatewayConfig,
    build_model_gateway_status,
    get_effective_cognee_embedding_config,
    get_effective_model_gateway_config,
)
from ai_anime.modules.model_usage.infrastructure.model_runtime import (
    get_effective_model_gateway_transport_config,
    get_model_access_json_transport,
    get_model_access_openai_client,
    get_model_reasoning_kwargs,
    get_model_gateway_credentials,
    get_text_pydantic_model,
    get_text_pydantic_model_settings,
    get_structured_output_litellm_kwargs,
    get_structured_output_model_settings,
    get_pydantic_model_settings,
)
from ai_anime.modules.model_usage.infrastructure.model_text_transport import (
    ModelTextTransportError,
    request_model_chat_content,
)
from ai_anime.modules.model_usage.infrastructure.protocol_errors import (
    model_protocol_error_message,
)
from ai_anime.modules.model_usage.infrastructure.video_request_usage import (
    count_video_beat_attempts,
    get_video_request_usage_db_path,
    get_video_usage_summary,
    record_video_request,
    update_video_request_status,
)


__all__ = [
    "DEFAULT_COGNEE_EMBEDDING_DIM",
    "DEFAULT_EMBEDDING_BATCH_SIZE",
    "EffectiveCogneeEmbeddingConfig",
    "EffectiveModelGatewayConfig",
    "MODEL_QUOTA_EXCEEDED_MESSAGE",
    "REMOTE_MODEL_QUOTA_CODE",
    "ModelQuotaExceededError",
    "ModelQuotaExceededStop",
    "MODE_MIXED",
    "MODEL_ACCESS_STDIN_ENV",
    "ModelAudioTransportError",
    "ModelAudioWriteResult",
    "ModelRoute",
    "ModelTextTransportError",
    "RuntimeModelAccess",
    "RuntimeModelAssignment",
    "RuntimeModelCapability",
    "build_model_gateway_status",
    "configure_model_access",
    "count_audio_scope_attempts",
    "count_image_scope_attempts",
    "count_video_beat_attempts",
    "find_model_quota_error",
    "find_model_quota_stop",
    "get_audio_request_usage_db_path",
    "get_effective_cognee_embedding_config",
    "get_effective_model_gateway_config",
    "get_effective_model_gateway_transport_config",
    "get_image_request_usage_db_path",
    "get_image_usage_summary",
    "get_model_access_json_transport",
    "get_model_access_openai_client",
    "get_model_reasoning_kwargs",
    "get_model_gateway_credentials",
    "get_text_pydantic_model",
    "get_text_pydantic_model_settings",
    "get_structured_output_litellm_kwargs",
    "get_structured_output_model_settings",
    "get_pydantic_model_settings",
    "get_video_request_usage_db_path",
    "get_video_usage_summary",
    "infer_episode_from_path",
    "infer_project_output_dir",
    "is_model_quota_error",
    "iter_exception_chain",
    "is_byok_allowed",
    "load_model_access_from_stdin",
    "model_access_configured",
    "model_protocol_error_message",
    "model_quota_payload",
    "normalize_video_workflow",
    "record_audio_generation_attempt",
    "record_image_request",
    "record_video_request",
    "request_model_chat_content",
    "require_model_admin_token",
    "resolve_model_assignment_for_role",
    "resolve_model_for_role",
    "resolve_model_route",
    "runtime_model_access",
    "runtime_model_capability",
    "serialize_model_access_for_subprocess",
    "update_audio_generation_attempt",
    "update_image_request_status",
    "update_video_request_status",
    "write_model_audio_music",
    "write_model_audio_speech",
    "write_model_audio_voice_design",
]
